apiVersion: v1
kind: Service
metadata:
  name: job222234567
spec:
  type: NodePort
  ports:
    - port: 80        # Service 暴露的端口
      targetPort: 20000 # Pod 中应用的端口
      nodePort: 30001  # 集群节点上的高端口
  selector:
    svc: job222234567      # 选择要关联的 Pod

